package org.techtown.project.predict;

public class Predict {

    public float solar_generation0;
    public float solar_generation1;
    public float solar_generation2;
    public float solar_generation3;
    public float solar_generation4;
    public float solar_generation5;
    public float solar_generation6;
    public float solar_generation7;
    public float solar_generation8;
    public float solar_generation9;
    public float solar_generation10;
    public float solar_generation11;
    public float solar_generation12;
    public float solar_generation13;
    public float solar_generation14;
    public float solar_generation15;
    public float solar_generation16;
    public float solar_generation17;
    public float solar_generation18;
    public float solar_generation19;
    public float solar_generation20;
    public float solar_generation21;
    public float solar_generation22;
    public float solar_generation23;
    public float solar_generation24;
    public float solar_generation25;
    public float solar_generation26;
    public float solar_generation27;
    public float solar_generation28;
    public float solar_generation29;
    public float solar_generation30;
    public float solar_generation31;
    public float solar_generation32;
    public float solar_generation33;
    public float solar_generation34;
    public float solar_generation35;
    public float solar_generation36;
    public float solar_generation37;
    public float solar_generation38;
    public float solar_generation39;
    public float solar_generation40;
    public float solar_generation41;
    public float solar_generation42;
    public float solar_generation43;
    public float solar_generation44;
    public float solar_generation45;
    public float solar_generation46;
    public float solar_generation47;
}